# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := MSM8916
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := msm8916
TARGET_BOARD_PLATFORM_GPU := qcom-adreno306

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53

# Kernel
BOARD_KERNEL_CMDLINE := console=null androidboot.hardware=qcom msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x80008000 --ramdisk_offset 0x81000000 --dt device/samsung/fortuna3g/dt.img --tags_offset 0x80000100
BOARD_KERNEL_SEPARATED_DT := true
TARGET_PREBUILT_KERNEL := device/samsung/fortuna3g/kernel

# Partition info
BOARD_HAS_LARGE_FILESYSTEM 		:= true
TARGET_USERIMAGES_USE_EXT4 		:= true
TARGET_USERIMAGES_USE_F2FS 		:= true
TARGET_PLATFORM_DEVICE_BASE 		:= /devices/soc.0/
BOARD_BOOTIMAGE_PARTITION_SIZE 		:= 13631488
BOARD_RECOVERYIMAGE_PARTITION_SIZE 	:= 15728640
BOARD_SYSTEMIMAGE_PARTITION_SIZE 	:= 1568669696
BOARD_USERDATAIMAGE_PARTITION_SIZE 	:= 5731479552
BOARD_FLASH_BLOCK_SIZE 			:= 131072

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true

# Qualcomm support
TARGET_RECOVERY_QCOM_RTC_FIX := true

# TWRP YOLO.
RECOVERY_VARIANT := twrp

# TWRP Configuration
BOARD_HAS_NO_SELECT_BUTTON 	:= true
BOARD_SUPPRESS_SECURE_ERASE 	:= true
BOARD_USE_CUSTOM_RECOVERY_FONT 	:= \"roboto_23x41.h\"
BOARD_HAS_NO_MISC_PARTITION 	:= true
BOARD_RECOVERY_SWIPE 		:= true
BOARD_USES_MMCUTILS 		:= true
BOARD_SUPPRESS_EMMC_WIPE 	:= true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_SDCARD_ON_DATA 	:= true
TARGET_RECOVERY_PIXEL_FORMAT 	:= "RGB_565"
TARGET_RECOVERY_DENSITY 	:= hdpi
TARGET_RECOVERY_QCOM_RTC_FIX 	:= true
TW_BRIGHTNESS_PATH 		:= "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS 		:= 255
TW_HAS_DOWNLOAD_MODE 		:= true
TW_HAS_MTP 			:= true
TW_INCLUDE_CRYPTO 		:= true
TW_INPUT_BLACKLIST 		:= "accelerometer\x0ahbtp_vm"
TW_INTERNAL_STORAGE_PATH 	:= "/data/media/0"
TW_DEFAULT_EXTERNAL_STORAGE 	:= true
TW_MTP_DEVICE 			:= /dev/mtp_usb
TW_NEW_ION_HEAP 		:= true
TW_NO_REBOOT_BOOTLOADER 	:= true
TW_NO_USB_STORAGE 		:= true
TW_TARGET_USES_QCOM_BSP 	:= false
TW_THEME 			:= portrait_hdpi
TW_INCLUDE_NTFS_3G 		:= true
TW_SCREEN_BLANK_ON_BOOT 	:= true

# Fstab
TARGET_RECOVERY_FSTAB := device/samsung/fortuna3g/recovery/twrp.fstab

BOARD_GLOBAL_CFLAGS += -DTW_USE_MINUI_CUSTOM_FONTS

# Vold
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_hsusb/gadget/lun%d/file
